### ISSUE TITLE
[Feature] Change order of sharing buttons

### ISSUE THREAD

**Issue by dartrax** [ankitrox/share-cart#10]
My AdBlocker "AdGuard" has a social media filter that hides the sharing icons for Facebook, Twitter and WhatsApp. This may result in an ugly display like this (only Facebook and Twitter activated):
![image](https://user-images.githubusercontent.com/15105943/86259700-a255d000-bbbc-11ea-886e-413904b3dc28.png)
This could be easily solved if Facebook, Twitter and Whatsapp would be at the end of the list. In this case, the window would automatically collapse like this:
![image](https://user-images.githubusercontent.com/15105943/86260781-07f68c00-bbbe-11ea-9b73-a7527bb66b72.png)

**Comment by ankitgadents** [comment]
Semantically this doesn't make sense to provide clipboard, save etc icon before social icons. However, I will introduce functionality to choose the order of the icons so that it depends on user how they want to place it.

**Comment by ankitgadents** [comment]
Marking this as won't fix in favour of https://github.com/ankitrox/share-cart/issues/12

**Comment by dartrax** [comment]
Thank you! That sounds great!
