### ISSUE TITLE
CSS changes other parts of website

### ISSUE THREAD

**Issue by dartrax** [ankitrox/share-cart#3]
Hi,
since I've updated from 1.0.8 to 2.0.1, other parts of the website get changed by css that is part of the share-cart-plugin.
The additional css comes from:
```
/wp-content/plugins/woo-save-and-share-cart/assets/js/build/scss/_nav.scss
/wp-content/plugins/woo-save-and-share-cart/assets/js/build/scss/_reboot.scss
/wp-content/plugins/woo-save-and-share-cart/assets/js/build/scss/_root.scss
/wp-content/plugins/woo-save-and-share-cart/assets/js/build/scss/_type.scss
/wp-content/plugins/woo-save-and-share-cart/assets/js/build/scss/vendor/_rfs.scss
```
Should the scope of the css not be limited to the plugin?

**Comment by ankitgadents** [comment]
Hi @dartrax,

Thanks for reporting the issues, but the mentioned `scss` path does not exist inside the build folder: https://plugins.svn.wordpress.org/woo-save-and-share-cart/trunk/assets/js/build/

Can you please provide the URL of the site and also double check the issue for me?

Regards,
Ankit

**Comment by dartrax** [comment]
Hi Ankit,
I think that those files are generated / compiled by SASS.

You can compare the page in question with version 1.0.8 and 2.0.1 here:
https://schlauhaus.biz/
https://schlauhaus.biz/wp_backup/

Look for differences in bottom border of Tabs, Underlines of Links, and the weight of header text.

**Comment by ankitgadents** [comment]
It has been handled in #5
